### ISSUE TITLE
`gofakeit.Struct()` panic on arrays

### ISSUE THREAD

**Issue by duckbrain** [brianvoe/gofakeit#113]
When a struct contains an array, `gofakeit.Struct()` panics because you can't append to an array. (It has a compile-time defined length.)

<summary>
Panic stack trace
<details>
<pre>
panic: reflect: call of reflect.Append on array Value

goroutine 1 [running]:
reflect.flag.mustBe(...)
	/usr/local/go-faketime/src/reflect/value.go:208
reflect.Append(0x563c80, 0xc000016180, 0x191, 0xc00006abb0, 0x1, 0x1, 0x0, 0x2, 0x0)
	/usr/local/go-faketime/src/reflect/value.go:2032 +0x200
github.com/brianvoe/gofakeit/v5.rSlice(0x601040, 0x563c80, 0x563c80, 0xc000016180, 0x191, 0x0, 0x0, 0x2)
	/tmp/gopath502901517/pkg/mod/github.com/brianvoe/gofakeit/v5@v5.9.0/struct.go:81 +0xe4
github.com/brianvoe/gofakeit/v5.r(0x601040, 0x563c80, 0x563c80, 0xc000016180, 0x191, 0x0, 0x0, 0x2)
	/tmp/gopath502901517/pkg/mod/github.com/brianvoe/gofakeit/v5@v5.9.0/struct.go:35 +0x232
github.com/brianvoe/gofakeit/v5.rStruct(0x601040, 0x56fae0, 0x56fae0, 0xc000016180, 0x199)
	/tmp/gopath502901517/pkg/mod/github.com/brianvoe/gofakeit/v5@v5.9.0/struct.go:58 +0x27f
github.com/brianvoe/gofakeit/v5.r(0x601040, 0x56fae0, 0x56fae0, 0xc000016180, 0x199, 0x0, 0x0, 0x0)
	/tmp/gopath502901517/pkg/mod/github.com/brianvoe/gofakeit/v5@v5.9.0/struct.go:23 +0x2e3
github.com/brianvoe/gofakeit/v5.rPointer(0x601040, 0x558280, 0x558280, 0xc000016180, 0x16, 0x0, 0x0)
	/tmp/gopath502901517/pkg/mod/github.com/brianvoe/gofakeit/v5@v5.9.0/struct.go:70 +0xff
github.com/brianvoe/gofakeit/v5.r(0x601040, 0x558280, 0x558280, 0xc000016180, 0x16, 0x0, 0x0, 0x0)
	/tmp/gopath502901517/pkg/mod/github.com/brianvoe/gofakeit/v5@v5.9.0/struct.go:21 +0x28e
github.com/brianvoe/gofakeit/v5.Struct(0x558280, 0xc000016180)
	/tmp/gopath502901517/pkg/mod/github.com/brianvoe/gofakeit/v5@v5.9.0/struct.go:15 +0xd1
main.main()
	/tmp/sandbox602772710/prog.go:15 +0x59
Program exited.
Syntax OK
</pre>
</details>
</summary>

```go
package main

import (
	"fmt"

	"github.com/brianvoe/gofakeit/v5"
)

type MyType struct {
	Values [4]string
}

func main() {
	v := MyType{}
	gofakeit.Struct(&v)
	fmt.Println(v)
}

```

https://goplay.space/#lR2MR_FXbQn

Instead it should loop through the length of the array and generate fakes for each element.

**Comment by brianvoe** [comment]
Interesting! Good catch. Ill try to tackle that soon

**Comment by brianvoe** [comment]
That was an interesting issue. I think i got it. I added some additional tests as well. Let me know if that works for you.
