### ISSUE TITLE
BitcoinPrivateKey produces invalid private key

### ISSUE THREAD

**Issue by cagriekin** [brianvoe/gofakeit#116]
Hi, 

I believe current implementation of `BitcoinPrivateKey` is aiming to generate `WIF` with the following implementation
```
func BitcoinPrivateKey() string {
	return "5" + Password(true, true, true, false, false, 50)
}
```

WIF keys should be satisfying `[5KL][1-9A-HJ-NP-Za-km-z]`. As allowed chars are `123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz` and the following are excluded `0OIl`.

Also `BitcoinPrivateKey` might be renamed as `BitcoinPrivateKeyWIF` for clarity.

Thanks

**Comment by brianvoe** [comment]
Interesting. Do you have an official websites you can point me to?

**Comment by cagriekin** [comment]
Sure, 
End result should satisfy [Base58](https://en.wikipedia.org/wiki/Base58) and I believe this article covers how to build a valid WIF private key [link](https://blog.qtum.org/wallet-import-format-3497f670b6aa)

**Comment by brianvoe** [comment]
Ok updated it to use base58 characters. Hopes that helps!
