### ISSUE TITLE
No random values generated

### ISSUE THREAD

**Issue by saurabh98s** [brianvoe/gofakeit#118]
` func  GenerateOneUser() (*User,error) {

	latitude,err:=gofakeit.LatitudeInRange(27.0,28.0)
	if err != nil {
		logger.Log.Errorln("[ERROR]",err)
		return nil,err
	}

	longitude,err:=gofakeit.LongitudeInRange(88.0,89.0)
	if err != nil {
		logger.Log.Errorln("[ERROR]",err)
		return nil,err
	}

	generatedUser := &User{
		Gender: gofakeit.Gender(),
		Name: gofakeit.Name(),
		Latitude: latitude,
		Longitude: longitude,
	}

	return generatedUser,nil

} `

`type User struct {
	Name      string
	Gender    string
	Latitude  float64
	Longitude float64
}`

while printing out a user i cant get random users
`user, err := user.GenerateOneUser()
	if err != nil {
		logger.Log.Errorln(err)
	}
	fmt.Printf("%v",user)`

it returns `&{Lina Carroll male 27.60466 88.940509}` each time

**Comment by brianvoe** [comment]
Need to make sure you seed. Easiest way is to run gofakeit.Seed(0), which will randomize it with unix nano timestamp. Otherwise you can run gofakeit.Seed(number you want to use here)
