### ISSUE TITLE
Is localization supported?

### ISSUE THREAD

**Issue by frederikhors** [brianvoe/gofakeit#119]
I don't understand if languages (localization, l18n) is supported.

E.g.: can I generate fake french first names?

**Comment by brianvoe** [comment]
Just english right now

**Comment by frederikhors** [comment]
Why are you closing it then? :smile:

**Comment by frederikhors** [comment]
Why are you closing it then? 😄

**Comment by brianvoe** [comment]
Cause its not an issue. Your asking for a feature request that i couldnt possible implement on my own.
