### ISSUE TITLE
How about generating different gofakeit in each goroutine?

### ISSUE THREAD

**Issue by GuqiloveQiyang** [brianvoe/gofakeit#126]
Hi, perfect package and good documents, good job.

I have one question:

- can i generate different gofakeit instance in each goroutine

Actually, i want to fake lots of different data in different formats. I use goroutine to process data, i want to generate different instance for each goroutine and add different custom functions for it.  I have not achieved it. It seems that all goroutine use the same instance and only one goroutine custom functions performed when define the same field.

Any ideas? Thanks.

**Comment by brianvoe** [comment]
I understand the issue. I havent tested it and maybe you could do it to let me know if it works. But my first thought is if you need to have a bunch of goroutines and each one of them is generating the same data set what you could do is sleep delay incrementing each goroutine so each one of them isnt generating the same values at the same time.

Give it a try and if it works let me know and ill add an example to the readme file
