### ISSUE TITLE
Question: Is it possible to set function parameters for structs at runtime?

### ISSUE THREAD

**Issue by azerbe** [brianvoe/gofakeit#132]
As the title says, I would like to adjust the number of elements in a nested struct at runtime.
Right now I need to change the numbers in the json tags for every mutation.

**Comment by brianvoe** [comment]
Im not sure i fully follow. Can you send an example struct with comments to show me where your talking about?

**Comment by azerbe** [comment]
Sure. 

```
type File struct {
 	ShaId    string    `json:"shaId" bson:"shaId" validate:"required" fake:"{uuid}"`
 	Contents []Content `json:"contents" bson:"contents" validate:"required,dive" fakesize:"3"`
 }
```

I can hardcode the size of the Contents array like shown above and call the fake size function with the parameter when I call 
```
var file models.File
gofakeit.Struct(&file)
```

This will generate the data like expected, but is very static. 

Something like `gofakeit.Struct(&file).With("Contents", fakesize("3"))` would be very useful to me. :) It would also enable the (easy) creation of a (cobra) CLI Tool for dynamic testate generation.

**Comment by brianvoe** [comment]
I see the situation your talking about. I would suggest setting a variable of []Content, filling it up with random data and a random amount and then assigning it to your struct. Its a few extra steps but it facilitates your need.

Im open to a pr if you have an example in mind but your simple "With" example wouldn't facilitate the requirements needed.
