### ISSUE TITLE
What is the correct usage for generating a string from a regular expression using a struct tag?

### ISSUE THREAD

**Issue by dcs3spp** [brianvoe/gofakeit#142]
Hi,

Started using this library and like the feature for generating strings according to a regular expression! I am trying to use this to create random strings that satisfy a specific format and/or for a specific length.

I have managed to generate a string from a regular expression using ```gofakeit.Regex``` function. However, I cannot seem to managed the same functionality using a struct tag.

What is the correct usage for generating a string from a regular expression using a struct tag?

I have created a small example listing below that illustrates my attempt at this. This is also available at the following [go playground](https://play.golang.org/p/fpf8LOvlxnB).

```go
package main

import (
	"fmt"
	"github.com/brianvoe/gofakeit/v6"
)

type Foo struct {
	RegExpStr  string  `fake:"{regex:^[0-9]{0,16}$}"`
}


func main() {
	var f Foo
	gofakeit.Struct(&f)
	
	fmt.Println("Try and generate a random string of digits upto length 16 using regex")
	fmt.Println()
	fmt.Println()
	fmt.Println("RegExpStr Via Tag := ", f.RegExpStr)
	
	result := gofakeit.Regex(`^[0-9]{0,16}$`)
	fmt.Println("RegExp Via Function := ", result)
}
```

**Comment by brianvoe** [comment]
I see the issue. This is a good catch. The problem i have is all of the struct stuff gets thrown through the generate function and the generate function will loop through and identify things between curly brackets. So in your situation it found the {0,16} and couldn't find a function to run. If it doesn't find a suitable function to run it replaces it with a n/a. I think i have an idea of how to solve this but i may need a little time to test and hash it out. I'll try to keep you updated with what i come up with. Cause the other issue i have is what i come up with cant break backwards compatibility so there is that.

**Comment by dcs3spp** [comment]
Ok thanks @brianvoe 

In the meantime I have since read the section concerning custom tags. Created my own tag that uses the ```RegEx``` function:
```go
gofakeit.AddFuncLookup("text", gofakeit.Info{
		Category:    "custom",
		Description: "Return a text string between 0 and and a length specified in the tag",
		Example:     "ABCDEFGH",
		Output:      "string",
		Params: []gofakeit.Param{
			{Field: "length", Type: "int", Description: "Max length of text"},
		},
		Generate: func(r *rand.Rand, m *gofakeit.MapParams, info *gofakeit.Info) (interface{}, error) {
			l, err := info.GetInt(m, "length")
			if err != nil {
				return nil, err
			}
			regex := fmt.Sprintf(`^[A-Z]{0,%d}$`, l)
			return gofakeit.Regex(regex), nil
		},
	})
```

**Comment by brianvoe** [comment]
Oh thats a clever work around for now. Im confident i have a fix for this. But ill have to put a little time into it and test out some scenarios. But for now what you have is a good idea. Im glad you submitted a pr instead of just adding that lookup without telling me.

**Comment by dcs3spp** [comment]
Ok, many thanks for your help and response @brianvoe. In the meantime I will continue using the workaround for now and once the fix is in place will use that. 

Many thanks again, appreciated :)

**Comment by brianvoe** [comment]
Figured it out release v6.0.2

**Comment by dcs3spp** [comment]
Many thanks @brianvoe it now works with regex in struct tags. I will go ahead and remove some of my custom tags. 

Thanks again,

Appreciated :)

**Comment by brianvoe** [comment]
Glad it worked out for you. Have to be aware of escaping back slashes otherwise the tag wont pull it in properly. So let me know if you come across any oddities with it cause trying to do regexes in a struct tag im sure at some point has its limitation.

**Comment by dcs3spp** [comment]
Thanks again @brianvoe, ok will let you know if any further issue arises with struct tag for regex
