### ISSUE TITLE
Loop password generation panic

### ISSUE THREAD

**Issue by scafoglieri** [brianvoe/gofakeit#143]
In this code:

```
type Foo struct {
	Id   int
	Name string `fake:"{firstname}"`
	Pwd  string `fake:"{password}"`
}

func main() {
	var f Foo

	for ii := 0; ii < 1000; ii++ {
		gofakeit.Struct(&f)
		fmt.Printf("%v\n", f)
	}
}
```

when the loop has 100 as max it's ok, but on 300 or more I get a random panic (with 1000 always panic):

```
panic: runtime error: slice bounds out of range [7:5]

goroutine 1 [running]:
github.com/brianvoe/gofakeit/v6.generate(0xc0000607e0, 0x571b9f, 0xa, 0x571b94, 0xc00006ac00)
        /.../go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.0.2/generate.go:86 +0x13e2
github.com/brianvoe/gofakeit/v6.rString(0xc0000607e0, 0x6266c0, 0x57c960, 0x57c960, 0xc000060858, 0x198, 0x571b9f, 0xa)
        /.../go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.0.2/struct.go:125 +0x48
```

The error is on password generation: I think that the loop is fast but password generation is not (or, maybe, reflection, if used). Why? First because if you add a time.Sleep() in the loop all goes well.

Second, if you output dataVal from function generate(), you have the generated password (eg. "0neMK}{vy12,") and so the function thinks that { and } are delimiters for a tag and you get panic. And in fact, if you disable special chars in the password generation all goes well again.

Thanks in advance

**Comment by brianvoe** [comment]
Interesting and good catch! Fixed and pushed v6.0.3
