### ISSUE TITLE
Fuzz embedded type with an array

### ISSUE THREAD

**Issue by tpoxa** [brianvoe/gofakeit#148]
Hi. Thanks for the awesome library. It helped me a lot!

Anyway, I found an issue which I don't know how to solve.  I am trying to fuzz the structure provided by gochimp,
gochimp3.CampaignResponse

It has embed type 
`withLinks`

```
type withLinks struct {
	Link []Link `json:"_link"`
}
```

When I do ```gofakeit.Struct(&gochimp3.CampaignResponse{})``` it left array of a links equals nil

```
(*gochimp3.CampaignResponse)(0xc0001aca00)({
 withLinks: (gochimp3.withLinks) {
  Link: ([]gochimp3.Link) <nil>
 },
 ID: (string) (len=19) "gowubpqygkqyqygtnvo",
 WebID: (uint) 0,
 Type: (string) (len=19) "gyxpllrycezdzkxsrxu",
 CreateTime: (string) (len=19) "obbzezktpgxwjvbzinn",
 ArchiveUrl: (string) (len=19) "gfrpzstvzlruupgvbqa",
 LongArchiveUrl: (string) (len=19) "jiuhtemmhcbpgpmobrx",
// ...
```

Any help is very appreciated.

**Comment by brianvoe** [comment]
Looks like withLinks is a private struct. Gofakeit(in fact no other package) does not have access to unexpected fields. Even if the subfield of the private field is public. Im open to hearing if someone can access a public field via a sub private field but thats my current understanding.

**Comment by tpoxa** [comment]
Problem is that somehow another library (github.com/alecthomas/jsonschema) generates jsonschema with private fields. 
Wonder how they do that? And can gofakeit do the same?

So my fuzzied object does not match the schema which was generated for it.

```
sch := jsonschema.Reflect(gochimp3.CampaignResponse{})
data, _ := sch.MarshalJSON()
	
```

```
 "CampaignResponse": {
      "required": [
        "_link",
...
```

**Comment by brianvoe** [comment]
Holy crap! I figured it out. Ill do a release shortly.

**Comment by brianvoe** [comment]
Did a release v6.1.1

Test it out and let me know if it works for your gochimp implementation.

**Comment by tpoxa** [comment]
It works now! Thank you very much!

```
(*gochimp3.CampaignResponse)(0xc0001c8a00)({
 withLinks: (gochimp3.withLinks) {
  Link: ([]gochimp3.Link) (len=2 cap=2) {
   (gochimp3.Link) {
    Rel: (string) (len=9) "BBCAAYbEH",
    Href: (string) (len=4) "KLdd",
    Method: (string) (len=4) "zQCt",
    TargetSchema: (string) (len=8) "BwfHUAhB",
    Schema: (string) (len=8) "RauJedZN"
   },
   (gochimp3.Link) {
    Rel: (string) (len=4) "FFeF",
    Href: (string) (len=8) "pxuFdGDe",

**Comment by brianvoe** [comment]
Nice! Glad to hear. I better see you staring the repository!!! 😄
