### ISSUE TITLE
Allow slice to be passed to Struct or create Array/Slice function

### ISSUE THREAD

**Issue by krhubert** [brianvoe/gofakeit#149]
Hi,

It would be nice if Struct can populate slice/array without wrapping it into a struct. Example below:

```go
package main

import (
  "testing"

  "github.com/brianvoe/gofakeit/v6"
)

type person struct {
  Name string `fake:"{name}"`
}

func TestPassSlice(t *testing.T) {
  persons := make([]person, 10)
  gofakeit.Struct(&persons)

  if persons[0].Name == "" {
    t.Errorf("slice not populated")
  }

  gofakeit.Struct(&struct {
    Persons []person
  }{persons})
  if persons[0].Name == "" {
    t.Errorf("struct not populated")
  }
}
```

```
$ go test 
--- FAIL: TestPassSlice (0.00s)
    gofakeit_test.go:18: slice not populated
FAIL
exit status 1
```

**Comment by brianvoe** [comment]
I agree with this. I should have all the functions i need in order to make this happen. Let me take a crack at it.

**Comment by brianvoe** [comment]
Ok pushed. v6.2.0 I added a function called Slice.

Example usage: 
```go
var S []string
Slice(&S)

I := make([]int8, 3)
Slice(&I)

type Basic struct {
  S string `fake:"{firstname}"`
  I int
  F float32
}

var B []Basic
Slice(&B)

```

**Comment by brianvoe** [comment]
Let me know if that works for you.

**Comment by brianvoe** [comment]
Plus i better see you in the github stars list! 😄

**Comment by krhubert** [comment]
@brianvoe 

>Let me know if that works for you. 

It works, thanks 🥰 


>Plus i better see you in the github stars list! 😄

Oh no, I don't know how it happened. Let me fix that unforgivable mistake. Done 😃

**Comment by brianvoe** [comment]
Ok good I almost had to call the cops on you for not staring it.
