### ISSUE TITLE
Date struct annotation not working

### ISSUE THREAD

**Issue by gadelkareem** [brianvoe/gofakeit#152]
```
Test struct {
        CreatedAt   time.Time `json:"created_at" fake:"{date}"`
    }
```

This always ends up with `"created_at":"0001-01-01T00:00:00Z"` 

Is that a bug?

**Comment by brianvoe** [comment]
I think i might try to look into setting time.Time field. Let me try to see what i can come up with

**Comment by brianvoe** [comment]
Added time.Time to the fields that can be generated in a struct. Check out the readme and test for example usages. v6.3.0

Let me know if that works for you.

**Comment by gadelkareem** [comment]
Yep! thanks a lot that worked!

Is it possible to also add `daterange` and something like `{date:now}`?

**Comment by brianvoe** [comment]
the problem with date range is the values take in time.Time and its hard to do that in a tag string

**Comment by gadelkareem** [comment]
yeah date range is not possible indeed. But I think `{date:now}` is achievable, right?

**Comment by brianvoe** [comment]
I could add that but data:now isnt a random thing. It would be weird for me to add something that doesnt generate a random data value.

**Comment by gadelkareem** [comment]
It makes since for attributes like `CreatedAt` and `UpdatedAt`

**Comment by brianvoe** [comment]
Agree to disagree. 😄
