### ISSUE TITLE
Custom Tag in Nested Struct

### ISSUE THREAD

**Issue by enricozb** [brianvoe/gofakeit#153]
Is it possible to use custom functions for struct fields? For example, I'm trying to fake the following struct:
```
type DBRow {
  Name sql.NullString `fake:"{nullstring}"`
}
```
where `sql.NullString` is just
```
struct {
  String string
  Valid bool
}
```

In order to do so, I'm adding the following function:
```
gofakeit.AddFuncLookup("nullstring", gofakeit.Info{
	Category:    "custom",
	Description: "Random sql.NullString with names as the possible strings",
	Example:     `sql.NullString{String: "non-random-value", Valid: true}`,
	Output:      "sql.NullString",
	Generate: func(r *rand.Rand, m *gofakeit.MapParams, info *gofakeit.Info) (interface{}, error) {
		if gofakeit.Bool() {
			return sql.NullString{
				String: "non-random-value",
				Valid:  true,
			}, nil
		}

		return sql.NullString{}, nil
	},
})
```

It looks like that `gofakeit` is recursing into the struct instead of respecting my custom function. Am I using the tags incorrectly?

**Comment by brianvoe** [comment]
No what you have looks correct I think your best bet is to set the field tag to skip and fill in the field after the fact.

I would have to look into this further to see whats going on. but its at least a good example cause i have null string fields that i would like to randomly generate with.

**Comment by enricozb** [comment]
I'm pretty sure what is happening is that in `struct.go`, you have a special case for stopping the recursion into nested structures, but that only happens `time.Time`: https://github.com/brianvoe/gofakeit/blob/425ab1f3321604172bd6688b6879b7a5f08947f2/struct.go#L60-L64

I think there should be some logic in here to see that, if there is a tag on the structure, then it should be replaced, not recursed  into.

I can try adding it sometime this week and sending over a PR if you'd like.

**Comment by brianvoe** [comment]
I think i see where your going with this. I would be open to a pr if you have a fix in mind. So time.Time is a special case. The only reason I added it was because it is part of the core library.

In this situation I would look into stopping from going further down into another struct if a fake tag is on the struct that could fill that sub struct out.

**Comment by brianvoe** [comment]
I got it working give it a shot and let me know if it worked for you. v6.4.0
