### ISSUE TITLE
index out of range [-1]

### ISSUE THREAD

**Issue by moranpatrick** [brianvoe/gofakeit#155]
Intermittently seeing the following error when testing our service under load.

```go
panic: runtime error: index out of range [-1]

goroutine 4967775 [running]:
math/rand.(*rngSource).Uint64(...)
	/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc000285500, 0x550e6d2c3b5961b8)
	/go/src/math/rand/rng.go:234 +0x93
math/rand.(*Rand).Int63(...)
	/go/src/math/rand/rand.go:85
math/rand.(*Rand).Int31(...)
	/go/src/math/rand/rand.go:99
math/rand.(*Rand).Int31n(0xc0002bef60, 0xc0000003e5, 0xc00036a680)
	/go/src/math/rand/rand.go:134 +0x5f
math/rand.(*Rand).Intn(0xc0002bef60, 0x3e5, 0xf552db)
	/go/src/math/rand/rand.go:172 +0x45
github.com/brianvoe/gofakeit/v6.getRandValue(0xc0002bef60, 0xc0036b71a0, 0x2, 0x2, 0xc0036b72c0, 0x4aad20)
	/root/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.0.2/helpers.go:67 +0xd4
github.com/brianvoe/gofakeit/v6.word(0xc0002bef60, 0x20, 0x1)
	/root/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.0.2/words.go:71 +0x97
github.com/brianvoe/gofakeit/v6.sentenceGen(0xc0002bef60, 0xa, 0xfc83d8, 0x24, 0x0)
	/root/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.0.2/words.go:111 +0xe0
github.com/brianvoe/gofakeit/v6.sentence(...)
	/root/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.0.2/words.go:84
github.com/brianvoe/gofakeit/v6.Sentence(...)
	/root/go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.0.2/words.go:78
```

Exception occurs when populating the body of a proto message with 10 words.
`Body:            faker.Sentence(10)`

After the service recovers it continues working as expected.

Release: v6.3.0

**Comment by brianvoe** [comment]
I just ran a long running for loop of 1 trillion gofakeit.Sentence(10) and didnt get any index out of range issues. Plus your panic is showing you that the panic is happening in your math rand package way far away from essentially is the last gofakeit call of getRandValue. Might want to look a little deeper into what system your running that would cause this issue. But I dont believe it has anything to do with gofakeit.

If that changes and you figure out your issue let me know cause it is interesting to see unique problems people come across.

**Comment by mkobaly** [comment]
I ran into the same issue. Maybe its not clear but if your doing concurrent fakes you should not use the default global faker or Rand. I switched to Crypto and it works fine. Here is a simple example to reproduce the issue

```

func main() {
        //Comment out two below lines and you will get a panic. Using Crypto faker as global works
	fake := gofakeit.NewCrypto()
	gofakeit.SetGlobalFaker(fake)

	for i := 0; i < 50000; i++ {
		go runFake()
		go runFake()
		go runFake()
		runFake()
		fmt.Print(".")
	}
	fmt.Println("Done..")
}

func runFake() {
	for i := 0; i < 900000; i++ {
		_ = gofakeit.Person()
	}
}
```
