### ISSUE TITLE
v6.4.*: float64 is not assignable to type sql.NullFloat64

### ISSUE THREAD

**Issue by KinaneD** [brianvoe/gofakeit#159]
Running v6.2.2 i had no issues running tests.
Though i faced issues with time.time values that were addressed in v6.3.0 as per this [issue](https://github.com/brianvoe/gofakeit/issues/152).
So i updated to the latest version v6.4.1, causing the below error. Downgrading to v6.4.0 did not solve the issue, same error persisted, going down to v6.3.0 took care of it.

### Struct definition
```
type Member struct {
	User
	FemaleAudience sql.NullFloat64 `gorm:"type:double precision;index;" fake:"{float64range:20,100} default:"nil"`
	MaleAudience     sql.NullFloat64 `gorm:"type:double precision;index;" fake:"{float64range:20,100}  default:"nil"`
}
```

### Seed
`gofakeit.Struct(&Member)`

### Error
```
panic: reflect.Set: value of type float64 is not assignable to type sql.NullFloat64 [recovered]
	panic: reflect.Set: value of type float64 is not assignable to type sql.NullFloat64

goroutine 12 [running]:
testing.tRunner.func1(0xc0000f9100)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0xcb0540, 0xc0001b6a80)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.assignTo(0xca7100, 0xc000223fc8, 0x18e, 0xe2d0c2, 0xb, 0xd54a40, 0x0, 0xca7100, 0xc000223fc0, 0x8e)
	/usr/local/go/src/reflect/value.go:2403 +0x432
reflect.Value.Set(0xd54a40, 0xc000486ee0, 0x199, 0xca7100, 0xc000223fc8, 0x18e)
	/usr/local/go/src/reflect/value.go:1537 +0xbd
github.com/brianvoe/gofakeit/v6.rStruct(0xc000464ea0, 0xfb26c0, 0xd54a40, 0xd54a40, 0xc000486ee0, 0x199, 0xcd7d55, 0x15)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:104 +0x7c8
github.com/brianvoe/gofakeit/v6.r(0xc000464ea0, 0xfb26c0, 0xd54a40, 0xd54a40, 0xc000486ee0, 0x199, 0xcd7d55, 0x15, 0xffffffffffffffff)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:34 +0x377
github.com/brianvoe/gofakeit/v6.rStruct(0xc000464ea0, 0xfb26c0, 0xe0bb00, 0xe0bb00, 0xc000486e58, 0x199, 0x0, 0x0)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:144 +0x2d5
github.com/brianvoe/gofakeit/v6.r(0xc000464ea0, 0xfb26c0, 0xe0bb00, 0xe0bb00, 0xc000486e58, 0x199, 0x0, 0x0, 0xffffffffffffffff)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:34 +0x377
github.com/brianvoe/gofakeit/v6.rStruct(0xc000464ea0, 0xfb26c0, 0xd981e0, 0xd981e0, 0xc000486c00, 0x199, 0x0, 0x0)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:144 +0x2d5
github.com/brianvoe/gofakeit/v6.r(0xc000464ea0, 0xfb26c0, 0xd981e0, 0xd981e0, 0xc000486c00, 0x199, 0x0, 0x0, 0x0)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:34 +0x377
github.com/brianvoe/gofakeit/v6.rPointer(0xc000464ea0, 0xfb26c0, 0xd84640, 0xd84640, 0xc000486c00, 0x16, 0x0, 0x0, 0x0)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:156 +0xf1
github.com/brianvoe/gofakeit/v6.r(0xc000464ea0, 0xfb26c0, 0xd84640, 0xd84640, 0xc000486c00, 0x16, 0x0, 0x0, 0x0)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:32 +0x2fb
github.com/brianvoe/gofakeit/v6.structFunc(0xc000464ea0, 0xd84640, 0xc000486c00)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:26 +0xe5
github.com/brianvoe/gofakeit/v6.Struct(...)
	/code/.go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.4.0/struct.go:16
```

Is it possible to support this again in newer versions as it was previously in v6.3?
The inability to assign primitive types to SQL's nullable primitive types, would prevent usage of the package in these cases, introduces inconsistency in the code base, where in some instances we just fake the struct while in others we don't, tests would become difficult to maintain, etc.

**Comment by brianvoe** [comment]
So this is a bit tricky cause it is not possible to set a float64 to a sq.NullFloat64. That being said I am not a fan of it panicing on you so Ill see what i can do to at least not panic it.

**Comment by KinaneD** [comment]
Thank you @brianvoe , that would be a good first step. I see that you already released v6.5 that takes care of that 💪
Could you please shed some light on why it's not possible anymore. I quickly looked into v6.4 release [commit](https://github.com/brianvoe/gofakeit/commit/3199cfdf847f7107b47ae7fa3d94af009bc53882) but could not spot it.

**Comment by ishando** [comment]
FYI: On upgrading from 6.3 to 6.5 I get the same type of error for sql.NullString for
```golang
	Email      sql.NullString `db:"email_address"       fake:"{email}"`
```
workaround: i created a custom function to generate the value, as i have only a few of these fields

Question: would it be possible to have a custom function accept a gofakeit function to generate the value so that one custom function could be used for multiple fields? possibly something like:

`  fake:"{nullstring:{email}}" `

**Comment by brianvoe** [comment]
you can add a lookup. https://github.com/brianvoe/gofakeit#custom-functions
