### ISSUE TITLE
Random generator race condition

### ISSUE THREAD

**Issue by botchris** [brianvoe/gofakeit#160]
global random generator is internally being used by gofakeit, [which is known to be non-thread safe](https://github.com/golang/go/issues/3611).

This produces multiple unexpected errors when using gofakeit on tests running with `-race` flag.

```
WARNING: DATA RACE
Read at 0x00c00044c000 by goroutine 41:
--
321 | math/rand.(*rngSource).Uint64()
322 | /usr/local/go/src/math/rand/rng.go:239 +0x3e
323 | math/rand.(*rngSource).Int63()
324 | /usr/local/go/src/math/rand/rng.go:234 +0x1d9
325 | math/rand.(*Rand).Int63()
326 | /usr/local/go/src/math/rand/rand.go:85 +0x85
327 | math/rand.(*Rand).Int31()
328 | /usr/local/go/src/math/rand/rand.go:99 +0x9a
329 | math/rand.(*Rand).Int31n()
330 | /usr/local/go/src/math/rand/rand.go:134 +0x4f
331 | math/rand.(*Rand).Intn()
332 | /usr/local/go/src/math/rand/rand.go:172 +0x59
333 | github.com/brianvoe/gofakeit/v6.getRandValue()
334 | /go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.3.0/helpers.go:67 +0x2ee
335 | github.com/brianvoe/gofakeit/v6.color()
336 | /go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.3.0/color.go:11 +0x266
337 | github.com/brianvoe/gofakeit/v6.Color()
338 | /go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.3.0/color.go:6 +0x1c1
....
```

**Comment by brianvoe** [comment]
I think where i land with this is if this is your issue you can always use your own as long as you adhere to rand.Source

**Comment by agis** [comment]
For posterity, it looks like the issue was addressed with a subsequent commit: https://github.com/brianvoe/gofakeit/commit/8d308391291017a02489455a82c01b3c2ecf76b7.

**Comment by brianvoe** [comment]
Yep. I added a variation of different source types. The main default one uses a mutex lock and is thread safe. If you want blazing fast generation and dont need it to be thread safe there is a source for that as well.

**Comment by brianvoe** [comment]
Sorry if this is a bit out of my wheelhouse but from my understanding having the mutex lock on the struct you have and when Int63() is run you lock and unlock in that function so your safely accessing the rand.Source64 value.

```go
type lockedSource struct {
	lk  sync.Mutex
	src rand.Source64
}

func (r *lockedSource) Int63() (n int64) {
	r.lk.Lock()
	n = r.src.Int63()
	r.lk.Unlock()

	return
}
```

I dont fully follow if your usage. Whether its gofakeit or its your own implementation of your own source.
