### ISSUE TITLE
Generate Stacktraces

### ISSUE THREAD

**Issue by kishaningithub** [brianvoe/gofakeit#163]
It would be great if we have the ability to generate stack traces

**Comment by kishaningithub** [comment]
Sames of stacktraces of various languages can be found here

https://github.com/mingrammer/flog/issues/32#issuecomment-720639436

**Comment by brianvoe** [comment]
I am open to adding individual pieces that would make filling out a stack trace easier. But full stack traces are a little more complicated to generate and might be a little out of scope for something like gofakeit

**Comment by kishaningithub** [comment]
@brianvoe Thanks for the response and support! :-) 

Since generating full stack traces are out of scope for this project.. Closing this issue

However will create separate Issues & PRs for individual components to help generate the same

**Comment by brianvoe** [comment]
Pr looked good. I merged it in. Ill do a release shortly
