### ISSUE TITLE
Add various types of sentence structures

### ISSUE THREAD

**Issue by brianvoe** [brianvoe/gofakeit#183]
https://medium.com/countdown-education/10-sentence-structure-types-you-should-recognize-with-examples-ebb198aca784

**Comment by Bhupesh-V** [comment]
Do we want this to work behind the scenes with `gofakeit.Sentence()`? 
or do we need a separate method for this

because I doubt developers in general we'll know about all the different types of sentences 😅

**Comment by brianvoe** [comment]
So currently I am building a better word list together, basically a more extensive list of specific types of verbs and nouns. Then ill put together a list of various sentence structures that people can use like gofakeit.SentenceSimple() and gofakeit.SentencePeriodic(). Then I will have gofakeit.Sentence() randomly pick between one of the sentence structures.

**Comment by brianvoe** [comment]
Added sentence simple
