### ISSUE TITLE
fake filenames & mime types

### ISSUE THREAD

**Issue by Bhupesh-V** [brianvoe/gofakeit#189]
I think the ability to add fake file names would be good. Something along these lines ..

```go
imageType := gofakeit.MimeType()
// "image/jpeg"
objectName := gofakeit.FileName()
// "random-string.jpg"
anotherFile := gofakeit.FileName(imageType)
```

if this sounds useful, let me know I can go ahead and submit a PR 🙌🏽

**Comment by brianvoe** [comment]
I already have fileextention and filemimetype but if you want to come up with a way to generate a filename that can optionally take in an extension I would be ok with that
