### ISSUE TITLE
[Help Needed] Combine Multiple Random Sources?

### ISSUE THREAD

**Issue by Mestrace** [brianvoe/gofakeit#192]
Let's say I would like to generate a random term from one of Foods, Beers and Games. Is there any way I could do this by defining my struct?
```
type Foo struct {
  Bar BarType // bar type is one of foods, beers and games
}

// how to define BarType
```

**Comment by brianvoe** [comment]
Looks like you may want to add your own lookup and add those lookups to your struct tags. The readme should have enough examples for you to go off of.
