### ISSUE TITLE
Compiling to windows 386 fails:  number.go: constant 18446744073709551615 overflows uint

### ISSUE THREAD

**Issue by dosco** [brianvoe/gofakeit#197]
⨯ release failed after 733.16s error=failed to build for windows_386: exit status 2: # github.com/brianvoe/gofakeit/v6
Error: ../../../go/pkg/mod/github.com/brianvoe/gofakeit/v6@v6.14.2/number.go:46:71: constant 18446744073709551615 overflows uint

**Comment by brianvoe** [comment]
Im open to pr's but I wouldnt know how to even test this. May I ask why you are trying to run it on that old machine?

**Comment by brianvoe** [comment]
Oh wow I think i pin pointed the issue. Its basically for all 32 bit systems. I think i have a fix for it. Ill try to keep you updated

**Comment by brianvoe** [comment]
Ok i added a fix for v6.14.3

**Comment by brianvoe** [comment]
Let me know if it worked and let me know why you are still using window 386

**Comment by dosco** [comment]
I am not using windows 386 I use goreleaser to build and release various versions of my app windows 386 is one of the defaults it builds.

**Comment by brianvoe** [comment]
oh interesting. its hard for me to test 32 bit system cause when i do test 32 bit systems it changes the randomizer and then all my tests are incorrect. I wouldnt mind supporting even 16 and 8 bit but other than making sure it builds I cant ensure rely on tests cause i get different outputs
