### ISSUE TITLE
Change the data-set of the generator

### ISSUE THREAD

**Issue by PumpkinSeed** [brianvoe/gofakeit#198]
**Feature idea**

The ability to change the data-set what the gofakeit uses for generating random data. So basically override the data.Firstname to use our own set of Firstnames.

**Use-case**

Let's say for database obfuscation, where I have a database of candidates for job opportunities what I filled with thousands of parsed resumes from LinkedIn. I want to test over the data-set, but I don't want to let the developers use this production data. So I just get all of the fields like Firstname, Lastname, etc. and feed into gofakeit. So the gofakeit engine can be used for own purposes.

**Comment by brianvoe** [comment]
Sounds good to me! Ill try to add this soon. Shouldnt be too crazy.

**Comment by brianvoe** [comment]
Added v6.15.0
