### ISSUE TITLE
Extra Method Suggestions

### ISSUE THREAD

**Issue by jimthree** [brianvoe/gofakeit#2]
Hi, great work on gofakeit!  If you have time, there are a couple of methods that I used heavily in the Ruby Faker Gem, which ould be awesome to see make it over here:

- [Hipster](https://github.com/stympy/faker/blob/master/doc/hipster.md)
- [Beer](https://github.com/stympy/faker/blob/master/doc/beer.md)
- [Hacker](https://github.com/stympy/faker/blob/master/doc/hacker.md)

If these, or any other from [stympy/faker](https://github.com/stympy/faker) made it into gofakeit, I would be very grateful!

**Comment by brianvoe** [comment]
Thanks for the kind words!
I like these and i see some things in stympy that i can add too. Ill get on this.

**Comment by brianvoe** [comment]
got hipster in, going to add beer and hacker before I do a new release

**Comment by jimthree** [comment]
You hero!

Cheers!
Jim

**Comment by brianvoe** [comment]
Added Hipster, Beer and hacker. Updated version and pushed. Let me if this works for you.

Thanks.
