### ISSUE TITLE
dependsOn tag

### ISSUE THREAD

**Issue by paulohcosta1** [brianvoe/gofakeit#212]
Hi guys, just a thought here.

I was using the lib, great lib by the way, and I thought if it's possible to create a tag to determine that a tag depends on another tag, example: I have a tag called customCountries, and there are 3 values possible to return, US, BR or GB, if its generate BR, I want that another tag creates a result with BR results. At the moment I'm creating a global var and maps to generate values that depends of each other.

**Comment by brianvoe** [comment]
That is an interesting situation. What you can do is on your first custom function call return the string of the next custom function.

Tags loop through the tag string and looks for the curly brackets wraps and runs the functions in that curly bracket. So if you return from your first function a string "{customUS}" it will loop again see new curly brackets and run that function again.

```go
`fake:"{customCountries}"`

func customCountries() string {
    // Do your rand val here
    return "{customUS}" // Wrap them in curly brackets and it will loop again and run the function in the curl brackets {}
}
```

Hope that helps
