### ISSUE TITLE
daterange Implicit requirements

### ISSUE THREAD

**Issue by Meppo** [brianvoe/gofakeit#214]
no document, daterange(start,end,format)  get expected result requirements:

- contain format tag
- daterange param format same with tag 'format'

## no format

```golang
package main

import (
	"log"
	"time"

	"github.com/brianvoe/gofakeit/v6"
)

type T struct {
	Time time.Time `json:"time" fake:"{daterange:2021-01-16,2022-05-05,yyyy-MM-dd}"`
}

func main() {
	var tmp T
	gofakeit.Struct(&tmp)
	log.Println(tmp)
}
```

```bash
$ go run main.go
2022/10/16 10:00:00 {0001-01-01 00:00:00 +0000 UTC}
```

## add format

```golang
package main

import (
	"log"
	"time"

	"github.com/brianvoe/gofakeit/v6"
)

type T struct {
	Time time.Time `json:"time" fake:"{daterange:2021-01-16,2022-05-05,yyyy-MM-dd}" format:"2006-01-02"`
}

func main() {
	var tmp T
	gofakeit.Struct(&tmp)
	log.Println(tmp)
}
```

```bash
$ go run main.go
2022/10/16 10:00:00 {2021-02-24 00:00:00 +0000 UTC}
```

**Comment by brianvoe** [comment]
I dont know if i fully follow. The first example looks correct. 

If you could look at this file and maybe see where the issue is I can take a look at it.
https://github.com/brianvoe/gofakeit/blob/master/time.go

**Comment by Meppo** [comment]
> I dont know if i fully follow. The first example looks correct.
> 
> If you could look at this file and maybe see where the issue is I can take a look at it. https://github.com/brianvoe/gofakeit/blob/master/time.go


- should use the daterange(start,end,format) third param to parse timeOutput generated by generate(ra,tag)
 
[https://github.com/brianvoe/gofakeit/blob/master/struct.go](https://github.com/brianvoe/gofakeit/blob/master/struct.go)

### comment 1,2,3

```golang
func rTime(ra *rand.Rand, t reflect.StructField, v reflect.Value, tag string) error {
	if tag != "" {
		// 1. call {daterange:2021-01-16,2022-05-05,yyyy-MM-dd} 
               // timeOutput = "2021-02-24"
		timeOutput := generate(ra, tag)

		// Check to see if they are passing in a format	to parse the time
		timeFormat, timeFormatOK := t.Tag.Lookup("format")
		if timeFormatOK {
			timeFormat = javaDateFormatToGolangDateFormat(timeFormat)
		} else {
			if tag == "{date}" {
				timeFormat = time.RFC3339
			} else {
				// Default format of time.Now().String()
                                // 2.  no extra format, will use this timeFormat
				timeFormat = "2006-01-02 15:04:05.999999999 -0700 MST"
			}
		}

		if len(timeOutput) > len(timeFormat) {
			timeOutput = timeOutput[:len(timeFormat)]
		}

		// 3. time.Parse("2006-01-02 15:04:05.999999999 -0700 MST", "2021-02-24")  will parse err 
                //       and return ,  set failed
		timeStruct, err := time.Parse(timeFormat, timeOutput)
		if err != nil {
			return err
		}

		v.Set(reflect.ValueOf(timeStruct))
		return nil
	}
}
```

**Comment by brianvoe** [comment]
I think i understand what your saying. The issue is the rTime is for the field type on the struct. When running generate I don't know that it may be using something that has a potential third parameter that is the format. Im open to ideas if you want to submit a pr.
