### ISSUE TITLE
Custom function for time attributes

### ISSUE THREAD

**Issue by mdvalv** [brianvoe/gofakeit#218]
Hello!

I'm trying to create a custom function to init some attributes with `time.Now()`, here's what I'm trying:

```go
package main

import (
	"fmt"
	"math/rand"
	"time"

	"github.com/brianvoe/gofakeit/v6"
)

func init() {
	gofakeit.AddFuncLookup("timenow", gofakeit.Info{
		Category:    "custom",
		Description: "Set the time to time.Now()",
		Output:      "time.Time",
		Generate: func(r *rand.Rand, m *gofakeit.MapParams, info *gofakeit.Info) (interface{}, error) {
			return time.Now(), nil
		},
	})
}

type Foo struct {
	Now time.Time `fake:"{timenow}"`
}

func main() {
	var foo Foo
	gofakeit.Struct(&foo)
	fmt.Println(foo.Now)
}
```

However, the value it prints on execution is always `0001-01-01 00:00:00 +0000 UTC`.
I am doing something wrong? Is there another way of achieving what I'm trying to do?
Here's also the [Go Playground code](https://go.dev/play/p/w80UOwhcOZk) for easier testing.

Thanks in advance and great job with this library!

**Comment by brianvoe** [comment]
I dont know why I felt the need to fix this today. It is a time parse error, you can see errors if you deal with them in the response of struct. time.Now() adds monotonic which wasnt being dealt with. v6.20.2
