### ISSUE TITLE
Add Movies (Titles, Genres) and Books (Titles, Genres, Authors)

### ISSUE THREAD

**Issue by dminkovski** [brianvoe/gofakeit#237]
Would love to work on this as well :)

**Comment by brianvoe** [comment]
I would love to see movies and books being added. The only concern I have is bloating it with too much data. I havent heard anyone complain about the size of gofakeit but I have to assume at some point people are going to say "I cant use it cause its too big"

But I think if you can come up with a decent but tight list we should be ok.
