### ISSUE TITLE
Add Future Date

### ISSUE THREAD

**Issue by hound672** [brianvoe/gofakeit#245]
Hi. 
Python's faker lib has [future_date](https://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html#faker.providers.date_time.Provider.future_date)

It's just shortcat for getting future time, instead of doing smth like:
```golang
time.Now().Add(time.hour * rand())
```

Don't you mind if I'll make PR?

**Comment by brianvoe** [comment]
If you want to add a pr I would be more than happy to add it. Just make sure it has the examples and benchmarks, lookup and readme.

**Comment by hound672** [comment]
> examples

I think it'd not to so easy, since result of `FutureDate` depends on current time.
