### ISSUE TITLE
SSN Formatting

### ISSUE THREAD

**Issue by bendyboo** [brianvoe/gofakeit#25]
You have the SSN formatted as ###-###-####, but it should be ###-##-####.  Please disregard if this is not for the US.

**Comment by brianvoe** [comment]
Hey @bendyboo thanks for pointing that out. Nice catch!

I updated it to be the correct length of numbers. I get some feedback awhile ago about not adding in the dashes so i decided to remove them for those who need the value not formatted. Hope this still works for you.

Thanks again!

**Comment by bendyboo** [comment]
Hey @brianvoe,
That's great, thanks for the quick update and for this great lib!

For me I actually do need the hyphenated version of the SSN, but I'm able to use your Numerify function to achieve this.  So as long as this function remains intact we should be fine.

Thanks again!

**Comment by brianvoe** [comment]
Sounds good. Glad you like it!
