### ISSUE TITLE
Is there a way to generate school or university name?

### ISSUE THREAD

**Issue by simhasrivatsa** [brianvoe/gofakeit#255]
It would help if we could generate school and university names

**Comment by brianvoe** [comment]
If you put together a pr. Ill take a look at it and see if we can get it merged in.

**Comment by wulfharth7** [comment]
I was working on this request, as I wanted to contribute but I have a question, I've created the data set in the datafolder as _"school.go"_ manually. And there is a string array in it of course.

In my school.go source code, where I generate the randomized data, i have a function called as SchoolGen like this

```
func schoolGen(r *rand.Rand) string { return getRandValue(r, []string{"school", "type"}) }
```

The thing is, it doesn't see my dataset with this, but when I use other dataset files, like **"minecraft", "ore"** it works.

Do you have a guess why? I've seen the readme.md in the **data folder** but it didnt quite make sense to me. 

Thanks.
