### ISSUE TITLE
nil values

### ISSUE THREAD

**Issue by halturin** [brianvoe/gofakeit#256]
I couldn't find how to enable the generation of nil values for my [][]float32 type. Could you please help me with this?

**Comment by PumpkinSeed** [comment]
Hi @halturin,

Can you please provide a use-case or explanation for what you want to see? I just don't understand what is the result what you want to get from gofakeit.

**Comment by halturin** [comment]
Thanks for your reply. 

i'm just expecting to see kind of [][]float32{nil, []float32{...}, nil, nil} or something. Currently, it fills all the values of any slice.

**Comment by PumpkinSeed** [comment]
As far as I know this is the closest solution, but it's not generating nil values:

```
package main

import (
	"fmt"

	"github.com/brianvoe/gofakeit/v6"
)

func main() {
	v := [][]float32{nil, []float32{12}, nil}
	gofakeit.Slice(&v)
	fmt.Println(v)
        // Output: [[6.5598885e+37 2.9083515e+38 1.9996555e+38 7.870126e+37 3.2749926e+37 2.658292e+38 1.0501455e+38] [1.4212272e+38] [1.647583e+38 2.382803e+38 3.0777828e+38 1.395749e+38 1.610417e+38]]
}
```

I think this requires some modification on the Slice function.

**Comment by halturin** [comment]
Unfortunately, it doesn't work. Imagine a multidimensional slice, say [][][][][]float32.

**Comment by PumpkinSeed** [comment]
@halturin I know it does not work, because I said: "I think this requires some modification on the Slice function."

This means that the Slice function does not support such a requirement, so someone needs to add this functionality. :)
Also probably it will be a new function, because of backward compatibility.

**Comment by brianvoe** [comment]
The problem with this is if i randomized a nil in an array of []float32 I would get the same issue from others wondering why im only partially filling out the array.

This is more of a user issue than anything. Sounds like you should make your own lookup function and output it the way you want.

**Comment by halturin** [comment]
Thanks for the reply. As soon as a slice/map can be nil, it's weird not to have the ability to assign nil as a value. It would be great to have another method like gofakeit.SliceWithNil(...) to add the probability of nil values. Up to you.

**Comment by brianvoe** [comment]
Im good. Thanks.
