### ISSUE TITLE
Adding other delimiters for the CSVOptions

### ISSUE THREAD

**Issue by dannkhoma** [brianvoe/gofakeit#257]
- Can you consider adding a semi colon delimiter or other delimiters on CSVOptions, currently only supporting "," and "/tab"

```
if co.Delimiter != "," && co.Delimiter != "\t" {
		return nil, errors.New("invalid delimiter type")
	}
```

**Comment by brianvoe** [comment]
Sure submit a pr and ill get it merged in

**Comment by brianvoe** [comment]
added will go out in new release
