### ISSUE TITLE
randomint is missing in function lookup

### ISSUE THREAD

**Issue by juanma9613** [brianvoe/gofakeit#258]
Hi, I just realized that the function randomint is not added here https://github.com/brianvoe/gofakeit/blob/master/number.go#L252

Is there any reason for that?

**Comment by brianvoe** [comment]
None of the numbers have a base like that. Number() returns an int if you need it

**Comment by edspc** [comment]
@brianvoe this makes it impossible to use `randomint` and `randomuint` in struct.
I receive such an error:
```
strconv.ParseUint: parsing "{randomuint:[1,2,3]}": invalid syntax
```
Can I open PR to fix this?
