### ISSUE TITLE
How to Sample strings based on file

### ISSUE THREAD

**Issue by juanma9613** [brianvoe/gofakeit#259]
Hi @brianvoe, I was exploring your library and I would like to ask you whether there's any way to create a function analogous to randomstring but which samples from a configurable list of options inside a file.

I almost managed to accomplish the task with the following piece of code, but the major drawback of my solution is that every time I generate a new random struct instance I need to read again the entire flights.txt file and it can have millions of rows. Are you aware any way of making it work without having to read the file multiple times?

This is my current solution, but keep in mind that nStructs can be above one million and the lines in the file can also be above one million:

~~~ go
package main

import (
	"fmt"
	"math/rand"
	"os"
	"strings"

	"github.com/brianvoe/gofakeit/v6"
)

func setup_gofakeit_with_custom() {
	faker := gofakeit.NewCrypto()
	gofakeit.SetGlobalFaker(faker)
	gofakeit.LogLevel("general")

	gofakeit.AddFuncLookup("randomstringfromfile", gofakeit.Info{
		Category:    "strings",
		Description: "Samples a single line from the provided path",
		Example:     "file contains [1 /n 2 /n 3 /n 4 /n 5 /n] => 4",
		Output:      "string",
		Params: []gofakeit.Param{
			{Field: "path", Type: "string", Description: "path to sample from"},
		},
		Generate: func(r *rand.Rand, m *gofakeit.MapParams, info *gofakeit.Info) (interface{}, error) {
			path, err := info.GetString(m, "path")
			if err != nil {
				return nil, err
			}

			// Drawback is that this reads the file every time it generates
			content, err := os.ReadFile(path)
			if err != nil {
				return nil, err
			}

			lines := strings.Split(strings.TrimSpace(string(content)), "\n")
			randLine := r.Intn(len(lines))

			if err != nil {
				return nil, err
			}
			res := lines[randLine]
			fmt.Printf("sampling flight %v from %v possibilities\n", res, len(lines))

			return res, nil
		},
	})
}

type MyStruct struct {
	Flights []string `fakesize:"2,5" fake:"{randomstringfromfile:flights.txt}"`
}

func main() {
	setup_gofakeit_with_custom()
	
	nStructs := 10
	for i := 0; i < nStructs; i++ {
	        var randomStruct MyStruct
		err := gofakeit.Struct(&randomStruct)
		if err != nil {
			fmt.Println("err", err)
		}

		fmt.Printf("Struct %+v \n", randomStruct)
	}
}
~~~

This is my flights.txt file in case it's useful:
~~~ txt
f1
f2
f3
f4
f5
~~~

The expected output will be something like:
~~~
Struct {Flights:[f1 f3]}
Struct {Flights:[f4 f1]}
Struct {Flights:[f3 f2]}
...
Struct {Flights:[f2 f4]}
~~~

Thank you very much, if you find an idea to implement this functionality and you would like me to send a PR, please let me know.

**Comment by brianvoe** [comment]
Sorry my github emails were being sent to spam for some reason.

This is more of a golang issue than a gofake it one. Throw your results in a global variable and just access the variable instead of re reading the file over and over again.
