### ISSUE TITLE
Note for required go version on readme

### ISSUE THREAD

**Issue by mingrammer** [brianvoe/gofakeit#26]
Hi.

I'm using your gofakeit in my cli open source, the [flog](https://github.com/mingrammer/flog)

Today, I've tried the installing the flog in centos:latest docker, but `go get` failed with `undefined: math.Round` error message. Yes, the `Round` method is available since Go 1.10. I didn't know it.

So, I think it is good idea that notes the required Go version on README to let users know the required Go version to use gofakeit.

How about you?

**Comment by brianvoe** [comment]
Oh good catch! Ill probably see if i can work it back so lower versions can use it.

**Comment by brianvoe** [comment]
Ok i replaced math.Round with math.Floor just cause the package itself is good for the earliest version of go. So i updated it and added v1.0 to travis to test against. So we should be good. v3.11.5

Thanks

P.S. It looks like you use a good amount of gofakeit in your package it would be really nice if you could put in your readme your use of gofakeit so it can help get some more eyes on the package.
