### ISSUE TITLE
Returning errors from gofakeit.Fakeable

### ISSUE THREAD

**Issue by jackwilsdon** [brianvoe/gofakeit#268]
It'd be useful if errors could be returned from fakeables, in the event that they call other functions which may return an error (e.g. `faker.Struct` to fake a sub-struct).

A new interface could be introduced for this:

```
type FakeableWithErr interface{
        // Fake returns a fake value for the type.
	Fake(faker *Faker) (interface{}, error)
}
```

Which could be used in `isFakeable` and `callFake`.

Alternatively, `callFake` could be updated to add special handling for the `error` type being returned in place of a value.

**Comment by jackwilsdon** [comment]
I don't think introducing an additional interface would be a breaking change?

**Comment by brianvoe** [comment]
If you go from 

```go
Fake(faker *Faker) interface{}
```
to
```go
Fake(faker *Faker) (interface{}, error)
```

Then yes it would technically be a breaking change.

**Comment by brianvoe** [comment]
I dont really want to implement and maintain both. I might just pull the trigger and change it.

**Comment by jackwilsdon** [comment]
I don't mind opening a PR for this if you're open to the linked implemention (i.e. introducing a new interface). It should only be a couple of lines of code in `isFakeable` and `callFake` and have a low maintenance burden. It'd be nice to keep backwards compatibility if possible.

**Comment by brianvoe** [comment]
It really should just have the error in there.
