### ISSUE TITLE
Unable to use it with reflect

### ISSUE THREAD

**Issue by alxarch** [brianvoe/gofakeit#27]
This library has an impressive collection of methods. 
Unfortunately, having all methods defined at top level without being able to instantiate a generator value forbids the use of reflect to inspect this package (ie templates, generators).
Think of a template filter with name "fakeit" and arguments method, args...
Or a tag on a struct field like fakeit:"email".
The only way to implement something like this right now is to write a huge switch statement and painstakingly map all function names manually.
Any plans of providing such an API?

**Comment by brianvoe** [comment]
I hear where you are coming from. Right now i dont have a good reason to add this given most individuals usage specifically call the function they need to use.

Maybe you can give me a better use case for this that i can grasp its importance to add.

Thanks.
