### ISSUE TITLE
package github.com/brianvoe/gofakeit/v6: cannot find package "github.com/brianvoe/gofakeit/v6" in any of:

### ISSUE THREAD

**Issue by jay0610** [brianvoe/gofakeit#270]
While installing package gofakeit receiving below error - 

[root@xxx ~]# go get github.com/brianvoe/gofakeit/v6 
package github.com/brianvoe/gofakeit/v6: cannot find package "github.com/brianvoe/gofakeit/v6" in any of:
        /usr/lib/golang/src/github.com/brianvoe/gofakeit/v6 (from $GOROOT)
        /root/go/src/github.com/brianvoe/gofakeit/v6 (from $GOPATH)
[root@xxx ~]# 

Server do have internet access however it fails with mentioned error. 
I am not sure if I am missing any step. 
Can I get help to resolve this issue ? 

Thanks in advance.

**Comment by brianvoe** [comment]
This just looks like a general local go issue. Package currently works as expected.
