### ISSUE TITLE
Better Descriptions

### ISSUE THREAD

**Issue by brianvoe** [brianvoe/gofakeit#277]
For each lookup there is a description of the function. The problem is they are a repeat of "Random {function}". Which seems useless.

Would be nice to have a more descriptive sentence that describes the function better.

**Comment by gy8534** [comment]
Hi @brianvoe, I wan to contribute for this issue. How can I get started?

**Comment by brianvoe** [comment]
Show me a couple of descriptions you would write and if that looks good you can make a pr to update the rest.

**Comment by brianvoe** [comment]
@se-omar great job on updating descriptions!
Let me know when your comfortably done so I can do the next release.

**Comment by se-omar** [comment]
Thanks, I have 3 more items to update.

I'll let you know when we're ready

**Comment by brianvoe** [comment]
no problem. no rush. just wasnt sure how close you were to being done

**Comment by se-omar** [comment]
ok i think that's all of them

**Comment by brianvoe** [comment]
ok sounds good! Ill do a release tonight.

**Comment by brianvoe** [comment]
https://github.com/brianvoe/gofakeit/releases/tag/v6.28.0
