### ISSUE TITLE
gofakeit.date() generate different date when using same seed.

### ISSUE THREAD

**Issue by gerayking** [brianvoe/gofakeit#278]
Hi, this is a great project, I'm having a small problem with it. When I used random seeds to generate dates, I found that using the same random seed would produce different results in different years (for example, 2023->2024), which caused my original unit_test to be wrong. I thought the same random seeds should produce same result
Example:
```go
func TestGenerateBySeed(t *testing.T) {
	gofakeit.Seed(10086)
	env := &ExpressionEnv{}
	args := []EvalResult{
		{type_: int16(sqltypes.VarChar),
			bytes_: []byte("timestamp")},
	}
	result := &EvalResult{}
	builtinGofakeitByType{}.call(env, args, result) // it will call gofakeit.Date()
	require.Equal(t, "1923-03-22 00:00:00", string(result.bytes_))
}
```
In 2024, it will generate '1950-03-22 00:00:00', but in 2023, the answer is '1923-03-22 00:00:00'. I found that the reason for the different outputs is due to the following code:
```go
func year(r *rand.Rand) int { return number(r, 1900, time.Now().Year()) }
```
I am not sure it is feature or bug?

**Comment by brianvoe** [comment]
ya once a year i have to update test examples and such, cause obviously the year changes. I need to set an end and it only makes sense to set it to the current year.

Ill have to think about this one. Open to suggestion.

**Comment by brianvoe** [comment]
P.S. Dont rely on a random generator for repeat values.

**Comment by gerayking** [comment]
I think it would be better to support two functions. The first one, Date(), would correct years ranging from 1900 to 2050. The second, DateRange(from Date, to Date), would support a range of dates.

**Comment by brianvoe** [comment]
https://github.com/brianvoe/gofakeit?tab=readme-ov-file#datetime
I already have those. and that doesnt fix year() though in your scenario.
