### ISSUE TITLE
Issues gotten from static analyzer

### ISSUE THREAD

**Issue by nd-cyberprotect** [brianvoe/gofakeit#353]
I ran static analyzer Svace and got critical issues:
- > After having been compared to a nil value at lookup.go:329 by calling function 'v6.Info.GetField' at lookup.go:259, pointer 'value[0]' is dereferenced at lookup.go:267.
- > After having been compared to a nil value at lookup.go:329 by calling function 'v6.Info.GetField' at lookup.go:299, pointer 'value[0]' is dereferenced at lookup.go:305.
- > After having been compared to a nil value at lookup.go:329 by calling function 'v6.Info.GetField' at lookup.go:361, pointer 'value[0]' is dereferenced at lookup.go:367.
- > After having been compared to a nil value at lookup.go:329 by calling function 'v6.Info.GetField' at lookup.go:377, pointer 'value[0]' is dereferenced at lookup.go:383.
- > After having been compared to a nil value at lookup.go:329 by calling function 'v6.Info.GetField' at lookup.go:393, pointer 'value[0]' is dereferenced at lookup.go:399.
- > After having been compared to a nil value at lookup.go:329 by calling function 'v6.Info.GetField' at lookup.go:409, pointer 'value[0]' is dereferenced at lookup.go:415.
- > After having been compared to a nil value at lookup.go:329 by calling function 'v6.Info.GetField' at lookup.go:425, pointer 'value[0]' is dereferenced at lookup.go:431.
- > After having been compared to a nil value at lookup.go:329 by calling function 'v6.Info.GetField' at lookup.go:441, pointer 'value[0]' is dereferenced at lookup.go:446.

There is no guarantee that method `GetField` returns not empty (including `nil`) slice. And there is no checks for for getting `value` as empty slice in methods `GetAny`, `GetMap`, `GetBool`, `GetInt`, `GetUint`, `GetFloat32`, `GetFloat64` and `GetString`. This potentially may cause panics.

Please add checks for getting empty slice where they need to be.

> version 6.26.4

**Comment by brianvoe** [comment]
https://github.com/brianvoe/gofakeit/blob/master/lookup.go#L260 GetField will return error if field not found.

**Comment by brianvoe** [comment]
https://github.com/brianvoe/gofakeit/commit/163b487242aee020e15867381c23ce70ed61fc57
