### ISSUE TITLE
Struct tag generator ignores fake tag for json.RawMessage fields

### ISSUE THREAD

**Issue by konatacarneiro** [brianvoe/gofakeit#360]
In [struct.go:35](https://github.com/brianvoe/gofakeit/blob/9d251357d0de7aad6477894fe91c29432e1fa78f/struct.go#L35), `r()` calls `rJsonRawMessage` if the field type is specifically `json.RawMessage`:
```go
	if t.PkgPath() == "encoding/json" {
		// encoding/json has two special types:
		// - RawMessage
		// - Number

		switch t.Name() {
		case "RawMessage":
			return rJsonRawMessage(f, v)
		case "Number":
			return rJsonNumber(f, v, tag)
		default:
			return errors.New("unknown encoding/json type: " + t.Name())
		}
	}
```

In [json.go:257](https://github.com/brianvoe/gofakeit/blob/9d251357d0de7aad6477894fe91c29432e1fa78f/json.go#L257), `rJsonRawMessage()` does not take a tag parameter and instead generates a JSON with completely random JSONOptions (default).

```go
func rJsonRawMessage(f *Faker, v reflect.Value) error {
	b, err := f.JSON(nil)
	if err != nil {
		return err
	}

	v.SetBytes(b)
	return nil
}
```

This makes it impossible to customize the generation of `json.RawMessage` fields using struct tags - there's no way to provide my own JSON generators, or to provide options to the default JSON generator.

Furthermore, I can't use the `[]byte` type as a workaround, since the slice generator uses the tag parameter to customize the generation of each individual element, not the generation of the whole slice itself.

**Comment by konatacarneiro** [comment]
My suggestion: substitute the code in the "RawMessage" case in #struct.go for this:
```go
		case "RawMessage":
			if tag != "" {
				err := rCustom(f, v, tag)
				if err == nil && v.CanInterface() {
					jsonData := v.Bytes()
					if !json.Valid(jsonData) {
						return errors.New("custom function returned invalid json data: " + string(jsonData))
					}
				}
				return err
			} else {
				return rJsonRawMessage(f, v)
			}
```

**Comment by brianvoe** [comment]
ya i think im good with adding a tag to that function. ill look out for your pr. just a reminder dont forget about tests. should be easy to add them as well.

Thanks
