### ISSUE TITLE
Documents for struct tag syntax and parameters?

### ISSUE THREAD

**Issue by ttc0419** [brianvoe/gofakeit#363]
The README.md only has an example of struct tags, any chance to have a list of all struct tags with parameters and the description of its syntax, like how to only specify fields field using csv?

**Comment by brianvoe** [comment]
Sorry i dont follow what your talking about. Can you send me an example of what your talking about?

**Comment by brianvoe** [comment]
I mean technically you could put all the params needed for a csv or sql but I wouldn't recommend it for struct tags.
