### ISSUE TITLE
Custom faker functions

### ISSUE THREAD

**Issue by torwald-sergesson** [brianvoe/gofakeit#48]
It will be fine to have ability to register custom functions which can be used in in structure tags:
```
func MyStrangeName() string {
    return "strange name"
}

type MyStruct struct {
    name string `fake:"my_strange_name"`
}

func main() {
    gofakeit.RegisterString("my_strange_name", MyStrangeName)
    // apply
   var s MyStruct
   gofakeit.Struct(&s)   
}
```

**Comment by brianvoe** [comment]
I do like that idea when i have the time to put more work into the struct part of gofakeit ill be sure to add that. Thanks

**Comment by brianvoe** [comment]
This was added in version 5. I implemented what call FuncLookups you can run AddLookupData and that will register custom functions that will be available in struct building.
