### ISSUE TITLE
Random generate is not seeded.

### ISSUE THREAD

**Issue by screwyprof** [brianvoe/gofakeit#49]
It's worth mentioning in the docs that the library users must init random with some seed, otherwise the fake data won't be really random.

To put it simply, one should add some init code, e.g.:

	rand.Seed(time.Now().UnixNano())

**Comment by brianvoe** [comment]
Thats a fair point. Ill add something

**Comment by hbagdi** [comment]
Should this not be left up to the user?

**Comment by brianvoe** [comment]
I just added some text in the read me that says

"If you would like to ensure randomization on initial use be sure to seed it first." with a simple example
