### ISSUE TITLE
sometimes DomainName() returns domains with a space

### ISSUE THREAD

**Issue by dcardamo** [brianvoe/gofakeit#54]
It doesn't happen every time but sometimes domains will have a space character in them such as this one: "internalweb services.net"

Its invalid so it breaks test code.

**Comment by brianvoe** [comment]
Thats a great catch thanks for pointing that out. Ill add some safe guards to catch stuff like that

**Comment by brianvoe** [comment]
Fixed v3.19.1

**Comment by dcardamo** [comment]
Thanks Brian !
