### ISSUE TITLE
defined length numberstring

### ISSUE THREAD

**Issue by tetff** [brianvoe/gofakeit#60]
It would be awesome to have a function to create a defined length string containing only numbers. Something like:
```
gofakeit.NumericString(5) // returns "83756"
```

**Comment by brianvoe** [comment]
HOW DARE YOU QUESTION THE ALMIGHTY GOFAKEIT!!!

```go
Generate("#####") // This will replace with numbers
```

https://github.com/brianvoe/gofakeit/blob/master/generate.go for reference.

**Comment by brianvoe** [comment]
You can also use Numerify("#####") string
