### ISSUE TITLE
Space character in url domain 

### ISSUE THREAD

**Issue by noandrea** [brianvoe/gofakeit#61]
Hello, I tried gofakeit to generate random URLs, 
but one of the test failed due to a invalid domain in the URL:

```
Error: Received unexpected error:
parse http://www.forwardweb services.info/synthesize: invalid character " " in host name
```
is generating invalid urls an expected behaviour?

**Comment by brianvoe** [comment]
Its not, im going to run through a bunch of url output and see if i can fix possible spaces and anything else that i can improve upon

**Comment by brianvoe** [comment]
ok fixed. v4.2.1
