### ISSUE TITLE
How to add an email annotation to struct?

### ISSUE THREAD

**Issue by gadelkareem** [brianvoe/gofakeit#73]

**Comment by brianvoe** [comment]
Can you be more descriptive on what your trying to do please

**Comment by gadelkareem** [comment]
Got it thanks
```
User struct {
        Email                 string `fake:"{person.first}####@{person.last}.{internet.domain_suffix}"`
    }
```

It would be great if we have ready templates names that we can insert into the annotations like `fake:"email"`

**Comment by brianvoe** [comment]
Working on it i promise
