### ISSUE TITLE
Fakeit client instead of global/package vars/seed

### ISSUE THREAD

**Issue by ghostsquad** [brianvoe/gofakeit#78]
I'd like be able to create a "fakeit" client object that could be instantiated

Example usage:

```go
// parameter is the seed
f := gofakeit.New(0)
f.Name()
```

It is safe/expected to call `gofakeit.Seed(?)` many times? What happens?

**Comment by brianvoe** [comment]
gofakeit currently is globally seeded. Cant seed per instance.

**Comment by brianvoe** [comment]
Do you have a specific situation your trying to accomplish?

**Comment by ghostsquad** [comment]
Not have a global seed is what I'm trying to solve at least as an alternative, so that individual tests can manage the seed how they wish. Sometimes I want a static seed, other times I might want something dynamic.

**Comment by ghostsquad** [comment]
Also this was a feature request. By closing this are you not interested in supporting this feature, even if someone submits a PR?

**Comment by brianvoe** [comment]
If you want a static seed just run gofakeit.Seed(a number you want) and that will give you consistent value. You can see i do this in the source code for all the tests examples

**Comment by ghostsquad** [comment]
@ghostsquad 
> Not have a global seed is what I'm trying to solve at least as an alternative, so that individual tests can manage the seed how they wish. Sometimes I want a static seed, other times I might want something dynamic.

@brianvoe 
> If you want a static seed just run gofakeit.Seed(a number you want) and that will give you consistent value. You can see i do this in the source code for all the tests examples

right, so I want to configure it differently possibly by different tests

**Comment by brianvoe** [comment]
Then set the seed to whatever you want. If you have an idea for a pr im open to looking at it but i cant guarantee it will be merged in
