### ISSUE TITLE
Feature: 🔀 Ensure different

### ISSUE THREAD

**Issue by ghostsquad** [brianvoe/gofakeit#79]
I'd like to generate data, but also ensure that the data differs from one call to another within a specific scope. As an example:

```go
d1 := data{name: gofakeit.Name() }
d2 := data{name: gofakeit.Name() }
```

I want to guarantee that `d1.name` and `d2.name` are not the same. But I don't really care what the values are.

**Comment by brianvoe** [comment]
Unfortunately i don't control random. For your situation what i would do is create an array and do an infinite for loop and append to that array until i filled the array with all unique values.
