### ISSUE TITLE
HackerIngverb missing in FuncLookups

### ISSUE THREAD

**Issue by danieltrautmann** [brianvoe/gofakeit#85]
I noticed that `HackerIngverb` is missing in the FuncLookups.

The file `hacker.go` defines 6 functions for generating fake data, but only 5 are added during `addHackerLookup`.

I can provide a pull request. I just wanted to check if this is missing intentionally.

**Comment by brianvoe** [comment]
Thanks for pointing that out. fixed v5.4.1
