### ISSUE TITLE
Allow template "fake" tags for non-string field

### ISSUE THREAD

**Issue by mniak** [brianvoe/gofakeit#94]
I was trying hard to use `fake:"{number:1:4}"` in a `int` field in order to generate a number between 1 and for, and even tough I am still not sure about the exact syntax for multiple arguments for a function in a template string, I found that only strings fields will have the template applied.

**Comment by brianvoe** [comment]
fake:"{number:1,4}" you can also use regex. Ill be adding a couple more example in the struct example function. Hope this helps

**Comment by mniak** [comment]
No it does not work for `int` fields.
```
package main

import (
	"fmt"

	"github.com/brianvoe/gofakeit/v5"
)

type MyStruct struct {
	Number int `fake:"{number:1:4}"`
}

func main() {
	var s MyStruct
	fmt.Println("Number (before)", s.Number)
	gofakeit.Struct(&s)
	fmt.Println("Number", s.Number)
}
```

**Execution:**
```
Number (before) 0
Number -548706813772622257
```

**Comment by mniak** [comment]
It seems that for non-string values the template is not being used.

**Comment by brianvoe** [comment]
You are currently correct on this. It is on my list to utilize lookup functions to make sure they can assign to struct value types.

**Comment by brianvoe** [comment]
Fixed. Will go out in the next version
