### ISSUE TITLE
Struct - Add ability to use funclookups with all sub types. Ints, floats, etc...

### ISSUE THREAD

**Issue by brianvoe** [brianvoe/gofakeit#96]
Right now if i want to use the fake tag in a struct and use something like fake:"{number:1,10}" i can only use it for strings. Now that funclookups exists i can use that same fake tag for things like ints and such.

**Comment by jneo8** [comment]
Face the same issue.

**Comment by brianvoe** [comment]
I'm working on it. It will be added soon

**Comment by brianvoe** [comment]
Fixed. Will go out in the next update
